/**
 * PIR → Node.js backend generator (v0.4).
 *
 * Reads the app model from PIR (entities + forms) and emits a self-contained
 * Express server with:
 *   - a CRUD REST API for every database entity
 *   - POST endpoints for form submissions (server-side validation)
 *   - static serving of the generated React build
 *
 * Philosophy: Plainly describes WHAT (an entity with these fields, a form
 * that creates records); this generator decides HOW (Express + pg).
 */

import type { IRModule } from "../pir/ir.js"
import { toSnakeCase, quoteIdent } from "./sql.js"

export interface CodegenFile {
  path: string
  content: string
}

interface EntityInfo {
  name: string
  table: string
  fields: { name: string; column: string; type: string }[]
}

function collectEntities(module: IRModule): EntityInfo[] {
  return module.entities.map((e) => ({
    name: e.name,
    table: toSnakeCase(e.name),
    fields: e.fields.map((f) => ({
      name: f.name,
      column: toSnakeCase(f.name),
      type: f.type,
    })),
  }))
}

/** JS-safe identifier (for record property access). */
function toCamel(name: string): string {
  const snake = toSnakeCase(name)
  return snake.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase())
}

export function generateBackend(module: IRModule): CodegenFile[] {
  const entities = collectEntities(module)
  const appName = module.app?.name ?? module.name

  const files: CodegenFile[] = []

  files.push({
    path: "server/package.json",
    content: JSON.stringify(
      {
        name: `${toSnakeCase(appName)}-server`,
        version: "0.4.0",
        type: "module",
        scripts: {
          start: "node server.mjs",
          dev: "node --watch server.mjs",
        },
        dependencies: {
          cors: "^2.8.5",
          express: "^4.21.0",
          pg: "^8.13.0",
        },
      },
      null,
      2,
    ),
  })

  files.push({
    path: "server/db.mjs",
    content: `// Database connection — generated by Plainly v0.4
import pg from "pg"

export const pool = new pg.Pool({
  host: process.env.PGHOST ?? "localhost",
  port: Number(process.env.PGPORT ?? 5432),
  database: process.env.PGDATABASE ?? "${toSnakeCase(appName)}",
  user: process.env.PGUSER ?? "postgres",
  password: process.env.PGPASSWORD ?? "postgres",
})
`,
  })

  const routes = entities.map((e) => generateEntityRoutes(e)).join("\n")
  const forms = entities.map((e) => generateFormRoute(e)).join("\n")

  files.push({
    path: "server/server.mjs",
    content: `// ${appName} API server — generated by Plainly v0.4
// Plainly described the app; this file implements it.
import express from "express"
import cors from "cors"
import { pool } from "./db.mjs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const app = express()
app.use(cors())
app.use(express.json())

// ---- health ----
app.get("/api/health", (req, res) => res.json({ ok: true, app: ${JSON.stringify(appName)} }))

${routes}
${forms}
// ---- static frontend (generated React build) ----
const distDir = path.join(__dirname, "..", "client", "dist")
app.use(express.static(distDir))
app.get("*", (req, res) => res.sendFile(path.join(distDir, "index.html")))

const PORT = Number(process.env.PORT ?? 3001)
app.listen(PORT, () => {
  console.log("${appName} API running at http://localhost:" + PORT)
})
`,
  })

  // Form submissions are also plain CRUD POSTs; generate one per form found
  // in the module's ops for documentation purposes.
  return files
}

function generateEntityRoutes(e: EntityInfo): string {
  const cols = e.fields.map((f) => quoteIdent(f.column)).join(", ")
  const placeholders = e.fields.map((_, i) => `$${i + 1}`).join(", ")
  const camel = toCamel(e.name)
  const readAll = e.fields.map((f) => `${quoteIdent(f.column)} AS "${f.name}"`).join(", ")
  const updates = e.fields.map((f, i) => `${quoteIdent(f.column)} = $${i + 2}`).join(", ")

  return `
// ---- ${e.name} ----
app.get("/api/${camel}", async (req, res) => {
  const { rows } = await pool.query(
    \`SELECT id, ${readAll}, created_at FROM ${quoteIdent(e.table)} ORDER BY id DESC\`)
  res.json(rows)
})

app.get("/api/${camel}/:id", async (req, res) => {
  const { rows } = await pool.query(
    \`SELECT id, ${readAll}, created_at FROM ${quoteIdent(e.table)} WHERE id = $1\`, [req.params.id])
  if (rows.length === 0) return res.status(404).json({ error: "${e.name} not found" })
  res.json(rows[0])
})

app.post("/api/${camel}", async (req, res) => {
  const values = [${e.fields.map((f) => `req.body[${JSON.stringify(f.name)}]`).join(", ")}]
  const { rows } = await pool.query(
    \`INSERT INTO ${quoteIdent(e.table)} (${cols}) VALUES (${placeholders}) RETURNING *\`, values)
  res.status(201).json(rows[0])
})

app.put("/api/${camel}/:id", async (req, res) => {
  const values = [req.params.id, ${e.fields.map((f) => `req.body[${JSON.stringify(f.name)}]`).join(", ")}]
  const { rows } = await pool.query(
    \`UPDATE ${quoteIdent(e.table)} SET ${updates} WHERE id = $1 RETURNING *\`, values)
  if (rows.length === 0) return res.status(404).json({ error: "${e.name} not found" })
  res.json(rows[0])
})

app.delete("/api/${camel}/:id", async (req, res) => {
  await pool.query(\`DELETE FROM ${quoteIdent(e.table)} WHERE id = $1\`, [req.params.id])
  res.status(204).end()
})
`
}

function generateFormRoute(e: EntityInfo): string {
  const camel = toCamel(e.name)
  return `
// ---- ${e.name} form endpoint (from Plainly form) ----
app.post("/api/forms/${camel}", async (req, res) => {
  const values = [${e.fields.map((f) => `req.body[${JSON.stringify(f.name)}]`).join(", ")}]
  const { rows } = await pool.query(
    \`INSERT INTO ${quoteIdent(e.table)} (${e.fields.map((f) => quoteIdent(f.column)).join(", ")}) VALUES (${e.fields.map((_, i) => `$${i + 1}`).join(", ")}) RETURNING *\`, values)
  res.status(201).json(rows[0])
})
`
}
