/**
 * Project generator (v0.4) — `plainly build app.pl`.
 *
 * Compiles source → PIR (validated) → SQL + Node backend + React frontend,
 * then writes a complete, runnable project:
 *
 *   my-app/
 *   ├── README.md             how to run the generated app
 *   ├── database/schema.sql   PostgreSQL DDL
 *   ├── server/               Express API (Node.js)
 *   └── client/               Vite + React + TypeScript frontend
 *
 * The generated app is standalone: it does not depend on Plainly at runtime.
 */

import { compileToPir } from "../pir/index.js"
import type { IRModule } from "../pir/ir.js"
import { generateSqlSchema, type SqlFile } from "./sql.js"
import { generateBackend, type CodegenFile } from "./node.js"
import { generateFrontend } from "./react.js"
import { PlainError } from "../errors.js"

export interface BuildResult {
  module: IRModule
  files: { path: string; content: string }[]
  /** Human-readable summary of what was generated. */
  summary: string[]
}

export function buildProject(source: string, options?: { appName?: string }): BuildResult {
  let module: IRModule
  try {
    module = compileToPir(source)
  } catch (err) {
    if (err instanceof PlainError) throw err
    throw err
  }

  const sql: SqlFile[] = generateSqlSchema(module)
  const backend: CodegenFile[] = generateBackend(module)
  const frontend: CodegenFile[] = generateFrontend(module)

  const appName = module.app?.name ?? module.name
  const snake = appName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "plainly-app"
  const entityCount = module.entities.length
  const pageCount = countPages(module)

  const readme = generateReadme(appName, entityCount, pageCount)

  const files = [
    { path: "README.md", content: readme },
    ...sql.map((f) => ({ path: f.path, content: f.content })),
    ...backend,
    ...frontend,
  ]

  const summary = [
    `App: ${appName}`,
    `Entities: ${entityCount}`,
    `Pages: ${pageCount}`,
    `Files: ${files.length}`,
    `  README.md`,
    ...sql.map((f) => `  ${f.path}`),
    ...backend.map((f) => `  ${f.path}`),
    ...frontend.map((f) => `  ${f.path}`),
  ]

  void options
  return { module, files, summary }
}

function countPages(module: IRModule): number {
  const main = module.functions[0]
  if (!main) return 0
  return main.blocks[0]?.ops.filter((o) => o.op === "ui.page").length ?? 0
}

function generateReadme(appName: string, entities: number, pages: number): string {
  return `# ${appName}

Generated by **Plainly v0.4** — \`plainly build\`.

A full-stack app: ${pages} page(s), ${entities} database entit${entities === 1 ? "y" : "ies"}.

## Run it

### 1. Database

Create a PostgreSQL database and load the schema:

\`\`\`bash
createdb ${appName.toLowerCase().replace(/[^a-z0-9]+/g, "_")}
psql -d ${appName.toLowerCase().replace(/[^a-z0-9]+/g, "_")} -f database/schema.sql
\`\`\`

(No PostgreSQL? Skip this step — the API will start but return errors until the
database exists.)

### 2. API server

\`\`\`bash
cd server
npm install
npm run dev        # → http://localhost:3001
\`\`\`

### 3. Frontend

\`\`\`bash
cd client
npm install
npm run dev        # → http://localhost:5173 (proxies /api to :3001)
\`\`\`

## What's inside

\`\`\`
database/schema.sql   PostgreSQL tables for every Plainly database
server/               Express API — CRUD for every entity + form endpoints
client/               Vite + React + TypeScript UI — one page per Plainly page
\`\`\`

## Regenerate

Change your \`.pl\` file, then run \`plainly build\` again. Generated files are
overwritten; put custom code elsewhere.
`
}
