/**
 * PIR → SQL schema generator (v0.4).
 *
 * Turns the module's entities into PostgreSQL DDL. Table/column names are
 * sanitized (snake_case) and every entity gets an auto-incrementing id plus
 * timestamps — the boring-but-critical defaults a real app needs.
 *
 * This generator never executes anything: it produces text files for the
 * project scaffold.
 */

import type { IRModule } from "../pir/ir.js"

export interface SqlFile {
  path: string // relative to the generated project
  content: string
}

/** Convert an entity/field name to a safe snake_case identifier. */
export function toSnakeCase(name: string): string {
  const snake = name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .toLowerCase()
    .replace(/^_+|_+$/g, "")
  return /^[a-z_]/.test(snake) ? snake : `t_${snake}`
}

const FIELD_TO_SQL: Record<string, string> = {
  text: "TEXT",
  number: "NUMERIC(12,2)",
  boolean: "BOOLEAN NOT NULL DEFAULT FALSE",
  money: "NUMERIC(12,2)",
  email: "TEXT",
  date: "DATE",
}

export function sqlTypeFor(fieldType: string): string {
  return FIELD_TO_SQL[fieldType] ?? "TEXT"
}

/** Quote an identifier so SQL reserved words (order, user, group…) are safe. */
export function quoteIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`
}

export function generateSqlSchema(module: IRModule): SqlFile[] {
  const statements: string[] = [
    `-- ${module.name} database schema`,
    `-- Generated by Plainly v0.4 (plainly build) — do not edit by hand`,
    ``,
  ]

  for (const entity of module.entities) {
    const table = toSnakeCase(entity.name)
    statements.push(`CREATE TABLE IF NOT EXISTS ${quoteIdent(table)} (`)
    statements.push(`  id SERIAL PRIMARY KEY,`)
    for (const field of entity.fields) {
      statements.push(`  ${quoteIdent(toSnakeCase(field.name))} ${sqlTypeFor(field.type)},`)
    }
    statements.push(`  created_at TIMESTAMPTZ NOT NULL DEFAULT now()`)
    statements.push(`);`)
    statements.push(``)
  }

  if (module.entities.length === 0) {
    statements.push(`-- This app declares no databases.`)
    statements.push(``)
  }

  return [
    {
      path: "database/schema.sql",
      content: statements.join("\n"),
    },
  ]
}
